### ISSUE TITLE
数据没有入库问题

### ISSUE THREAD

**Issue by baqianxin** [owner888/phpspider#10]
数据没有入redis，数据表也没有，但是跑起来也没有错误，有可能是什么问题啊

 Find list page: http://www.mafengwo.cn/gonglve/ajax.php?act=get_travellist&mddid=63515
23:00:53 Find list page: http://www.mafengwo.cn/gonglve/ajax.php?act=get_travellist&mddid=140736
23:00:53 Success process page: http://www.mafengwo.cn/mdd/base/list/pagedata_citylist?page=96   Use time: 0.338 s

23:00:53 Spider running time: 00 hour 02 minutes 10 seconds

23:00:53 Find pages: 1109

23:00:53 Waiting for collect pages: 1011

23:00:53 Collected pages: 98

**Comment by owner888** [comment]
马蜂窝的规则和其他不样例不同，因为都是ajax的列表，所以我是先生成列表页的，一般要半个小时才开始有数据，建议如果是测试样例的话，用qiushibaike.php

**Comment by baqianxin** [comment]
![image](https://cloud.githubusercontent.com/assets/6780391/19752806/9b27f1da-9c32-11e6-93eb-69a9cace498e.png)
是我的环境问题吗,依然是没有数据入库啊

**Comment by baqianxin** [comment]
可以了，等待时间稍长一点。谢谢你

**Comment by tianxianggezhu** [comment]
蚂蜂窝数据没有入库请问是怎么回事？数据库没有问题，表没问题，程序可以跑，但是数据库就是空空如也？是不是mafengwo.php要取消//'save_running_state' => true,的注释是不？

**Comment by tianxianggezhu** [comment]
之前有尝试过取消注释，但是取消注释后，运行会提示phpspider.php的低555行            self::$configs['name'] = mb_convert_encoding(self::$configs['name'], "gbk", "utf-8");有问题，我尝试注释后，结果程序好像在执行就是啥都不显示。

**Comment by tianxianggezhu** [comment]
找到原因了，城市列表页执行完之后不会继续执行文章列表页所以就没有数据，请问该怎么办？

**Comment by baqianxin** [comment]
其实一直都是对的，配置好数据库之后，你只需要耐心等待30分钟左右
