### ISSUE TITLE
可以提供一个离线文档吗

### ISSUE THREAD

**Issue by 838514984** [owner888/phpspider#106]
网上的文档不全啊

**Comment by kingleoric** [comment]
我也需要一个离线的

官方doc.phpspider.org经常断断续续打不开，过几分钟又好，作者能解决一下吗？

**Comment by 838514984** [comment]
可以正常浏览的时候存档了一份，有需要的可以下载
链接：https://pan.baidu.com/s/1vqaYuCRJq_niT4ADKwcokw 密码：jltw

**Comment by owner888** [comment]
@838514984 谢谢提供文档，用心了，其实QQ群里面有pdf文档哈

**Comment by owner888** [comment]
@kingleoric 因为用的是gitbook的，偶尔会被墙，QQ群里面有pdf文档

**Comment by owner888** [comment]
@kingleoric QQ群：147824717
