### ISSUE TITLE
求助：log有find list page但是不走on_list_page回调

### ISSUE THREAD

**Issue by 838514984** [owner888/phpspider#107]
![qq 20180527104021](https://user-images.githubusercontent.com/20331198/40582002-9794fa84-619a-11e8-924a-40b688f1532e.jpg)
不走onlistpage回调额

**Comment by owner888** [comment]
@838514984 这个只能说明找到了列表页，但是这些列表页url在队列里面，on_list_page是列表页面被采集的时候才会出发的，找到列表页只是入到队列等待采集

**Comment by 838514984** [comment]
恩恩，这些我都已经解决了，谢谢回复！ @owner888
