### ISSUE TITLE
是用demo中的qiushibaike.php,无法导出csv或者sql

### ISSUE THREAD

**Issue by adminspaceplatform** [owner888/phpspider#135]
rt， 生成了data目录 但是没有.csv或者.sql 不知道是什么问题

**Comment by owner888** [comment]
应该是采集不到内容导致，你看看日志是否显示已经提取到了内容

**Comment by adminspaceplatform** [comment]
在get_field中var dump $html 是有结果的 但是因为在phpspider.php的2084行把$field设置成了空数组 导致跳过了很多if语句 并且这个函数的return值也成了空

**Comment by adminspaceplatform** [comment]
我想问在get field中$fields具体应该是什么？我看到$fields[$conf["attached_url]]所以应该是个包含url的数组吗

**Comment by adminspaceplatform** [comment]
我好像是找到原因了 默认的selector type是xpath 然后返回的values的值一个是一段字符串 一个是NULL，在foreach中给fields赋值再走到null又把fields给赋值成了空数组 所以导致fields最后是空的跳过了if语句所以没有输出 那么为什么values会返回一段字符串和一个null呢

**Comment by adminspaceplatform** [comment]
已解决 想请教一下可以爬取搜索引擎的结果吗
