### ISSUE TITLE
有没有类似python里PhantomJs的采集方式

### ISSUE THREAD

**Issue by zklknight** [owner888/phpspider#136]
有些页面事ajax渲染的数据，而且接口是加密过的  直接采不了接口。之前用py的PhantomJs模拟浏览器让ajax渲染出来采集的。请问这个框架怎么实现？

**Comment by owner888** [comment]
没有的，这个还不如直接抓ajax数据好用，ajax回来的数据一般是json，直接用json_decode就好了

**Comment by zklknight** [comment]
@owner888 
![微信图片_20190308165641](https://user-images.githubusercontent.com/26521492/54472762-0d816480-4809-11e9-8ea1-8b86d19dace9.jpg)
开启多任务，只有第一个进程有数据 其他一直是失败

**Comment by zklknight** [comment]
![1552724970(1)](https://user-images.githubusercontent.com/26521492/54472822-e4150880-4809-11e9-8c45-3af42ad55a35.jpg)
开多任务   只有第一个有数据  其他都是失败

**Comment by zklknight** [comment]
@owner888 
![Uploading 1552724970(1).jpg…]()
开多任务 只有第一个有数据 其他都是失败

**Comment by zklknight** [comment]
@owner888 
开多任务 只有第一个有数据 其他都是失败
![1552724970(1)](https://user-images.githubusercontent.com/26521492/54472844-68678b80-480a-11e9-9f05-252e08860d77.jpg)
