### ISSUE TITLE
发现一个过时函数 & 一个 bug

### ISSUE THREAD

**Issue by TianLanSky** [owner888/phpspider#154]
我写在博客里面啦

[点击进入](https://jsztl.com/index.php/2020/08/19/%e4%bf%ae%e5%a4%8d%e3%80%81%e6%9b%b4%e6%96%b0-phpspider-%e6%a1%86%e6%9e%b6/)

**Comment by owner888** [comment]
感谢您的支持，bug已经修复，但是你最后说的那个问题，看不懂，解决办法：在 重试url 入队之前，将 url 移出 self::$collect_urls

**Comment by TianLanSky** [comment]
你原来的代码：
爬取(url)
self::$collect_urls[md5(url)]=time();
爬取失败，重新入队 url
准备爬取 url，但是发现 self::$collect_urls[md5(url)] 已经定义，所以就不爬取了

修复：
爬取(url)
self::$collect_urls[md5(url)]=time();
爬取失败，重新入队 url，**并且 unset(self::$collect_urls[md5(url)])**
准备爬取 url，但是发现 self::$collect_urls[md5(url)] 已经定义，所以就不爬取了

**Comment by owner888** [comment]
感谢支持，已经修复
