### ISSUE TITLE
Ctrl-C无法终止

### ISSUE THREAD

**Issue by cuikangyi** [owner888/phpspider#20]
Ctrl-C无法正常终止终止，PHP version:7.0.8-0ubuntu0.16.04.3
不知道是不是环境的问题
加入`declare(ticks = 1);`后可使用Ctrl-C正常退出

**Comment by cuikangyi** [comment]
查了下ticks的资料，貌似这个没执行一句代码都会执行一次，比较影像性能
不知道有啥解决方案

**Comment by owner888** [comment]
谢谢你的反馈，5.x测试是没有问题的，我加上declare(ticks = 1);吧，稍后请更新代码哈

**Comment by cuikangyi** [comment]
OK
