### ISSUE TITLE
文档set_hosts($hosts)有小错误

### ISSUE THREAD

**Issue by CenJing** [owner888/phpspider#32]
[https://doc.phpspider.org/requests.html](url)

>$spider->on_start = function($phpspider) 
>{
>    $host = array(
>        'www.qiushibaike.com' => array(
>            "203.195.143.21",
>            "203.195.143.22"
>        ),
>    );
>    requests::set_hosts($hosts);
>};

`$host = array(...);` 的 $host 应为 $hosts

**Comment by owner888** [comment]
谢谢提醒，已经修改好

**Comment by BrainGithub** [comment]
为什么我看不到文档啊，打不开啊
