### ISSUE TITLE
使用 css 选择器的时候，可能会出错。

### ISSUE THREAD

**Issue by xczizz** [owner888/phpspider#45]
fields 中配置
 ```
'selector' => 'table > tr > td > h1',
'selector_type' => 'css',
```
会报错：PHP Fatal error: Call to undefined function pq() in ***\core\selector.php on line 236.
我吧这个改成`phpQuery::pq()`之后，也遇到了问题：
```
PHP Fatal error: Uncaught exception 'Exception' with message 'Can' use last created DOM, because there isn't any. Use phpQuery::newDocument() first." in ***\libary\phpQuery.php 4515
```
所以，我最后吧所有的css都改成了xpath 选择。到现在还在跑！

**Comment by hfvoip** [comment]
这个问题我在linux上遇到了，后来发现 sp_autoload 中加载phpQuery类的时候，，会去找phpquery.php ,不找phpQuery.php  ,见说明:http://php.net/manual/en/function.spl-autoload.php

我的解决方法是把phpQuery.php改名为phpquery.php

**Comment by owner888** [comment]
谢谢hfvoip，我去修改过来
