### ISSUE TITLE
遇到一个头疼的问题

### ISSUE THREAD

**Issue by ijackwu** [owner888/phpspider#62]
> 列表页:/a/100/
> 匹配表达式: /a/d+/

> 内容页:/a/100/xxx
> /a/d+/w+

这样内容页完全没办法找到，因为代码是优先匹配，列表页面的。这个栗子是想表达，能不能在加人list之前做一个回调方法判断。

**Comment by owner888** [comment]
你这样的写法不可能有问题，除非内容页是 /a/100/xxx/ 而不是 /a/100/xxx，就是有 / 结尾的，才会被 d+/ 匹配到，针对/a/100/xxx/这种内容页，你列表页的表达式，不应该这么写
