### ISSUE TITLE
php版本为7.1.7，导出为csv文件时路径出错。

### ISSUE THREAD

**Issue by serenehaly** [owner888/phpspider#67]
操作系统：Ubuntu16.04
PHP版本：7.1.7

问题描述：
csv导出路径为

> ../data/qiushibaike.csv

，能生成data目录，爬取内容是success的，但data目录没有生成对应的csv文件；

`'export' => array(
        'type' => 'csv',
        'file' => '../data/qiushibaike.csv',
    ),`

将csv导出路径修改为

> PATH_DATA.'/qiushibaike.csv'

，却生成了PATH_DATA文件夹，并且文件夹里生成对应的csv文件；

`'export' => array(
        'type' => 'csv',
        'file' => PATH_DATA . '/qiushibaike.csv',
    )`

这是什么问题呢？

**Comment by owner888** [comment]
../data/qiushibaike.csv 是你当前执行php的目录的上级目录哦，你看看清楚你的上级目录有没有data这个目录
