### ISSUE TITLE
[发现Redis中有采集数据, 是否继续执行, 不继续则清空Redis数据重新采集]这里好像不能清理啊

### ISSUE THREAD

**Issue by ieliwb** [owner888/phpspider#84]
public function check_cache()
    {
        if (!self::$use_redis || self::$save_running_state)
        {
            return false;
        }

        //if (queue::exists("collect_queue")) 
        $keys = queue::keys("*"); 
        $count = count($keys);
        if ($count != 0) 
        {
            // After this operation, 4,318 kB of additional disk space will be used.
            // Do you want to continue? [Y/n] 
            //$msg = "发现Redis中有采集数据, 是否继续执行, 不继续则清空Redis数据重新采集\n";
            $msg = "Found that the data of Redis, no continue will empty Redis data start again\n";
            $msg .= "Do you want to continue? [Y/n]";
            fwrite(STDOUT, $msg);
            $arg = strtolower(trim(fgets(STDIN)));
            $arg = empty($arg) || !in_array($arg, array('y','n')) ? 'y' : $arg;
            if ($arg == 'n') 
            {
                foreach ($keys as $key) 
                {
                    $key = str_replace($GLOBALS['config']['redis']['prefix'].":", "", $key);
                    queue::del($key);
                }
            }
        }
    }

Found that the data of Redis, no continue will empty Redis data start again
Do you want to continue? [Y/n]n
Notice: Undefined index: config in /home/www/xxxx/spider/phpspider/core/phpspider.php on line 2007
$key = str_replace($GLOBALS['config']['redis']['prefix'].":", "", $key);
提示这行有bug，我自己添加了config/inc_config.php这个文件还是一样，不能清理redis缓存的历史，请问怎么修改呢

**Comment by owner888** [comment]
不要意思这是一个bug，把$GLOBALS['config']['redis']改成self::$queue_config就好，新版本已经提交

**Comment by ieliwb** [comment]
谢谢，已解决
