### ISSUE TITLE
想问下 买了个阿布云的代理的问题

### ISSUE THREAD

**Issue by neciszhang** [owner888/phpspider#94]
你好大神，想请教问题
1.买了个阿布云动态版本的账号，我需要如何在代码里怎么书写才能使用呢，他的通行证书和通行证道怎么书写呢
2.爬取糗事百科大概爬取1000条，就有个滑动验证

**Comment by owner888** [comment]
qiushibaike.php用的就是阿布云的代理，你照这抄就好哈
